### ISSUE TITLE
run notificationReceivedHandler when app is terminated (in background)

### ISSUE THREAD

**Issue by lubritto** [IhorKlimov/Flutter-One-Signal#3]
I'm inserting the notification on database when i receive it, but if the app is closed the method doesn't run, how can i solve it ?

**Comment by IhorKlimov** [comment]
@lubritto I'm aware of this issue. As One Signal released their official plugin, I don't see any reason for pushing commits to this repo anymore, despite a having a simpler setup

**Comment by lubritto** [comment]
@IhorKlimov Ok Ihor, thanks for answer me!
